version: '3'

tasks:
  create-lambda-package:
    desc: Create a .zip deployment package for lambda.
    cmds:
      - ./src/scripts/create_lambda_package.sh {{.FUNCTION_PATH}} {{.FUNCTION_NAME}} {{.DEPENDENCIES_PATH}}
